server:
  port: 7001

spring:
  data:
    mongodb:
      port: 27017
      host: localhost
      database: product-db

logging:
  level:
    root: INFO
    com.prigovor: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

---

spring:
  profiles: docker

  data:
    mongodb:
      host: mongodb

server:
  port: 8080